#!/bin/sh

function cfg()
{
     cfg=`echo $1 | tr '[:lower:]' '[:upper:]' | sed 's/-/_/g'`
     echo "$cfg"
}

echo "/* Automatically generated by $0 */
struct cmdname_help
{
    char name[16];
    char help[80];
};

static struct cmdname_help common_cmds[] = {"

sed -n -e 's/^perf-\([^ 	]*\)[ 	].* common.*/\1/p' command-list.txt |
sort |
while read cmd
do
     echo "#ifdef CONFIG_BUILTIN_$(cfg $cmd)"
     sed -n '
     /^NAME/,/perf-'"$cmd"'/H
     ${
            x
            s/.*perf-'"$cmd"' - \(.*\)/  {"'"$cmd"'", "\1"},/
	    p
     }' "Documentation/perf-$cmd.txt"
     echo "#endif"
done

echo "#ifdef HAVE_LIBELF_SUPPORT"
sed -n -e 's/^perf-\([^ 	]*\)[ 	].* full.*/\1/p' command-list.txt |
sort |
while read cmd
do
     echo "#ifdef CONFIG_BUILTIN_$(cfg $cmd)"
     sed -n '
     /^NAME/,/perf-'"$cmd"'/H
     ${
            x
            s/.*perf-'"$cmd"' - \(.*\)/  {"'"$cmd"'", "\1"},/
	    p
     }' "Documentation/perf-$cmd.txt"
     echo "#endif"
done
echo "#endif /* HAVE_LIBELF_SUPPORT */"
echo "};"
