#ifndef BUILTIN_CMDS_H
#define BUILTIN_CMDS_H

#ifndef CONFIG_KBUILD
#define CONFIG_BUILTIN_REPORT 1
#define CONFIG_BUILTIN_SCRIPT 1
#define CONFIG_BUILTIN_BENCH 1
#define CONFIG_BUILTIN_SCHED 1
#define CONFIG_BUILTIN_TRACE 1
#define CONFIG_BUILTIN_TOP 1
#define CONFIG_BUILTIN_RECORD 1
#define CONFIG_BUILTIN_BUILDID_LIST 1
#define CONFIG_BUILTIN_INJECT 1
#define CONFIG_BUILTIN_LOCK 1
#define CONFIG_BUILTIN_KVM 1
#define CONFIG_BUILTIN_BUILDID_CACHE 1
#define CONFIG_BUILTIN_EVLIST 1
#define CONFIG_BUILTIN_KMEM 1
#define CONFIG_BUILTIN_STAT 1
#define CONFIG_BUILTIN_DIFF 1
#define CONFIG_BUILTIN_ANNOTATE 1
#define CONFIG_BUILTIN_TIMECHART 1
#define CONFIG_BUILTIN_LIST 1
#define CONFIG_BUILTIN_HELP 1
#define CONFIG_BUILTIN_PROBE 1
#define CONFIG_BUILTIN_MEM 1
#else
#include "generated/autoconf.h"
#endif /* CONFIG_KBUILD */

#endif /* BUILTIN_CMDS_H */
