obj-y += Context.o

CFLAGS_Context.o := $(PERL_EMBED_CCOPTS)
CFLAGS_Context.o += -Wno-redundant-decls -Wno-strict-prototypes
CFLAGS_Context.o += -Wno-unused-parameter -Wno-nested-externs
CFLAGS_Context.o += -Wno-undef -Wno-switch-default
