obj-y += header.o
obj-y += tsc.o
obj-$(CONFIG_BUILTIN_KVM_STAT) += kvm-stat.o
obj-$(CONFIG_LIBDWARF) += dwarf-regs.o
obj-$(CONFIG_LIBUNWIND) += unwind-libunwind.o
obj-$(CONFIG_LIBDWARF_UNWIND) += unwind-libdw.o
